### ISSUE TITLE
Listing error

### ISSUE THREAD

**Issue by Fnatic91** [insthync/UnityMultiplayerARPG_AuctionHouse#4]
Getting this error when i want to list an item in Auction house right after i click an item in inventory, any idea?

Latest kit version, auction house server running localhost.

![ahIssue](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/a9fd6f30-b1ea-4e4b-ab65-7649998ab664)

**Comment by insthync** [comment]
Did you setup proper URLs?

**Comment by Fnatic91** [comment]
Yes, set it to: http://127.0.0.1:9800

**Comment by Fnatic91** [comment]
![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/47bbced6-9d90-46b6-86b7-53863b9a9ed0)

**Comment by insthync** [comment]
Please capture screenshot of your `RestClient.cs` at around line `569`

**Comment by Fnatic91** [comment]
![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/0996f98f-81d6-4194-ab5a-6c094a8600fa)

**Comment by insthync** [comment]
What is null?, why the indent don't like mine?

**Comment by insthync** [comment]
After client joined a server, URLs value in game network manager changed?

**Comment by Fnatic91** [comment]
That is the question why it is null, its exactly the same just Visual studio moved a bit because i tryed to Debug.log it before i reported the error.

**Comment by Fnatic91** [comment]
This error happens with any item i trying to list, as soon as inventory came up and i clicking on any item ,the error happens.

**Comment by Fnatic91** [comment]
> After client joined a server, URLs value in game network manager changed?

one sec and checking!

**Comment by Fnatic91** [comment]
> After client joined a server, URLs value in game network manager changed?

Nope, remains the same.

**Comment by insthync** [comment]
As the log message telling, It is occurring when load auction price list (price for each duration and so on, I can't remember), the weird thing is why the url is null.

**Comment by Fnatic91** [comment]
Technically the error refers to that line of code so related to Duration options

![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/fe4d2e5a-dea3-4386-854c-f233e6d25f30)

**Comment by Fnatic91** [comment]
Right, seems url is empty but how since its being added correctly in the settings

**Comment by Fnatic91** [comment]
If im adding the URL this way than it works, however also needs to allow http connection in the project settings, so the question is why the AuctionRestCLient doesn't getting the URL.

![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/d0e50b79-43d2-409d-9d41-f5e1b2babf9f)

**Comment by Fnatic91** [comment]
Just checked: GetAuctionClientConfig(), result.ResponseCode is "Error"

**Comment by insthync** [comment]
Yep, I think that one is source of problem, do you know which kind of error?

**Comment by Fnatic91** [comment]
Sadly its just contains “Error” i made a debug.log to see the response code but it is “Error”

**Comment by insthync** [comment]
https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/commit/e80c54d24eefcd51f34b6b5d4c8e246907aad72c

**Comment by Fnatic91** [comment]
> [e80c54d](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/commit/e80c54d24eefcd51f34b6b5d4c8e246907aad72c)

So this change, solved the issue, nowclient receiving the URL and i was able to list item also:

![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/70a30c8f-441a-4756-950e-2f6695e35719)


Thank you!

**Comment by Fnatic91** [comment]
Now:

Buy out: "You are not allowed to do that"(have enough gold):
![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/5bf40a73-0e70-47cc-9ff5-3dc5cc3f5bce)


Clicking on Bid throwing this error:
![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/276cc9b0-3d77-4168-9173-f8a4b3d7c80e)

**Comment by insthync** [comment]
You may try to fix it then create a pull request, don't have to wait for me.

**Comment by Fnatic91** [comment]
> You may try to fix it then create a pull request, don't have to wait for me.

Removed the error and images, it was my bad!

Another character from same account can't buy out, which makes sense, buy out works with another account.

Bid throwing the error when bid field amount is 0 so the bidder not inputed any amount to bid, however incase it should tell, "Bid can't be 0" instead of throwing an error.

**Comment by insthync** [comment]
Can you help me to fix it?

**Comment by Fnatic91** [comment]
I can't open pull request but made a fix:

In UIAuctionList.cs


 public void OnClickBid()
        {
            if (!CacheSelectionManager.SelectedUI)
                return;
            if (inputBidPrice.text != "")
            {
                int bidPrice = int.Parse(inputBidPrice.text);
                CacheSelectionManager.SelectedUI.OnClickBid(bidPrice);
            }
            else 
            {
                UISceneGlobal.Singleton.ShowMessageDialog(LanguageManager.GetText(UITextKeys.UI_LABEL_ERROR.ToString()), LanguageManager.GetText(UITextKeys.UI_ERROR_NOT_ALLOWED.ToString()));
            }
        }


It wil lshow message panel insetad of throwing error, can't add better message withotu the neesd of modify the kit core parts like UITextKeys.cs, DefaultLocale.cs for betetr message.

**Comment by insthync** [comment]
Why can't make a pull request?

**Comment by insthync** [comment]
WHY?

**Comment by Fnatic91** [comment]
Sorry, bussy days, seems i just don't have access or something like that:

![image](https://github.com/insthync/UnityMultiplayerARPG_AuctionHouse/assets/27919632/1ec5e9d9-2442-4297-88e7-3080686a9920)


> WHY?

**Comment by insthync** [comment]
Create a  new branch, then push and make a new pull request
